### PR TITLE
add emilylange as trusted user

### PR DESCRIPTION
**Pull request by emilylange**
@mweinelt told me about this builder :)

I don't have a `darwin` machine.
Meaning, I can't debug failed package builds on `darwin`. Neither packages I maintain, nor those that I review.

I've been granted access to the _nixpkgs-committers_ team today :)
I hope this is enough to be considered a trusted user. If not, @mweinelt might be able to vouch for me :p 

That `sk-ssh-ed25519@openssh.com` is a non-interactive fido key.
I've tested and used this in the past with my remote builders. Should work.

The other key (`ssh-ed25519`) is a fallback, in case I lose my hardware token or if that `sk-` one does not work with `darwin` for whatever reason^^

### CODE REVIEW

**Comment by winterqt** [comment]
To my knowledge, FIDO2 SSH keys no longer work with macOS' SSH server. (They did in the past.)

Can you use a standard ed25519 or RSA key instead?

**Comment by emilylange** [comment]
aww, okay!
Removed the fido one and will use the one initially intended as fallback as primary instead. ty!

**Comment by winterqt** [comment]
Sorry for the delayed response. Can you please fix the merge conflict? Thanks!

**Review by winterqt — APPROVED** [review]

**Comment by emilylange** [comment]
thank you! :)

**Pull request merged**
