### PR TITLE
add ma27 as trusted user

### PR DESCRIPTION
**Pull request by Ma27**
Even though I don't do much darwin-related stuff, it's sometimes useful to have such a box, most recent case is the JIT support for postgresql[1].

Note: I purposely added uid 515 because #12 and #14 are in front of me in the queue ;-)

[1] https://github.com/NixOS/nixpkgs/pull/221851#issuecomment-1475153031

### CODE REVIEW

**Comment by winterqt** [comment]
Even though you tried to be smart, Git doesn't like cleverness :(

Can you rebase, please? Thanks!

**Comment by Ma27** [comment]
Rebased. Also figured that it should be 514 as #14 should also have conflicts that have to be rebased manually %)

**Comment by winterqt** [comment]
Smart :)

**Review by winterqt — APPROVED** [review]

**Comment by winterqt** [comment]
Deployed, thanks!

**Pull request merged**
