### PR TITLE
Add phaer as trusted user

### PR DESCRIPTION
**Pull request by phaer**
Hello @winterqt! 

I am looking for a darwin builder to test my work for [dream2nix](https://github.com/nix-community/dream2nix/), and @RaitoBezarius thankfully pointed out your project here :)

Just a remote builder to check if builds are working on macOS would already be immensely helpful! Something to integrate into CI later on would be even better, but I am not entirely sure about the security implications of that yet.

### CODE REVIEW

**Comment by RaitoBezarius** [comment]
I can vouch for @phaer, having met him at the Ocean Sprint.

**Comment by winterqt** [comment]
Please fix the merge conflict.

**Comment by phaer** [comment]
Just did so :)_

**Comment by winterqt** [comment]
Something's still up... no clue what. Guess GitHub can't rebase + merge when you add a merge commit. Can you rebase on top of main instead?

**Comment by phaer** [comment]
@winterqt ofc, done

**Review by winterqt — APPROVED** [review]

**Pull request merged**
